More files to bin

diff --git a/Ubuntu/bin/format-files b/Ubuntu/bin/format-files
--- a/Ubuntu/bin/format-files
+++ b/Ubuntu/bin/format-files
@@ -1,37 +1,129 @@
 #!/bin/bash
-if [[ ${#} -eq 1 && ("${1}" == "-help" || "${1}" == "-h") ]]
-then
+
+# -------------------------------------------------------------------------------------------------
+# Functions
+# -------------------------------------------------------------------------------------------------
+BASEDIR=$(dirname $(readlink -f ${0}))
+BASENAME=$(basename ${0})
+
+function usage {
   echo "Format files by finding and replacing patterns in filename"
-  echo "Usage: ${0} [<find>] [<replace>]"
-  echo "  - <find> : Pattern to find in the file name"
-  echo "  - <replace> : Pattern to replace in the file name"
+  echo ""
+  echo "Usage: ${BASENAME} [--find <find>] [--replace <replace>] [--rm <remove...>] [--dir <directory>] [--regex] [--recur]"
+  echo "  find    : String to find in the file's name. Optional. Defaults to ''"
+  echo "  replace : String to replace in the file's name. Optional. Defaults to ''"
+  echo "  rm      : String(s) to remove. Optional. Defaults to ''"
+  echo "  dir     : Dir to find files. Defaults to PWD."
+  echo "  regex   : Do a regular expression find/replace. Optional. Disabled by default."
+  echo "  recur   : Do a recursive search for all files in <dir>. Optional. Disabled by default."
+}
+
+function dieUsage {
+  local mesg=${1}
+  echo "Error: ${1}"
+  usage
+  exit 1
+}
+
+# -------------------------------------------------------------------------------------------------
+# Parse Arg
+# -------------------------------------------------------------------------------------------------
+if [[ ${#} -eq 1 && ("${1}" == "--help" || "${1}" == "-h") ]]
+then
+  usage
   exit 0
 fi
 
+# Default values
 find=""
-repl=""
-if [ ${#} -eq 1 ]
+replace=""
+rm=""
+dir="${PWD}"
+regex="false"
+recur="false"
+
+# Parse
+declare -A arg
+while [[ ${#} -gt 0 ]]
+do
+  case "$1" in
+    --find|--dir|--replace)
+      key=$(echo "${1}" | sed "s%^--%%")
+      arg[$key]="${2}"
+      shift 2
+    ;;
+
+    --rm)
+      key=$(echo "${1}" | sed "s%^--%%")
+      shift
+      while [[ ${#} -gt 0 && ! "${1}" =~ ^-- ]]
+      do
+        arg[$key]="${arg[$key]} ${1}"
+        shift
+      done
+      arg[$key]=$(echo "${arg[$key]}" | sed -re "s%^\s+%%" | sed -re "s%\s+$%%")
+    ;;
+
+    --recur|--regex)
+      key=$(echo "${1}" | sed "s%^--%%")
+      arg[$key]="true"
+      shift
+    ;;
+
+    *)
+      dieUsage "Unknown arg $1"
+    ;;
+
+  esac
+done
+
+# Get values
+find=${arg["find"]}
+replace=${arg["replace"]}
+dir=${arg["dir"]}
+rm=${arg["rm"]}
+recur=${arg["recur"]}
+regex=${arg["regex"]}
+
+cmd="find ${dir} -maxdepth 1 -type f"
+if [[ "$recur" == "true" ]]
 then
-  find=${1}
-elif [ ${#} -eq 2 ]
-then
-  find=${1}
-  repl=${2}
+  cmd="find ${dir} -type f"
 fi
 
-# Iterate through all files in current dir
-IFS=$'\n'
-for file in `ls -1`
+# Sample command to process output of command line by line:
+# while read -r line; do  echo $line; done < <(command)
+while read file
 do
-  new_file=$file 
-  if [ ! -z $find ]
+  newFilePath=$(dirname "$(readlink -f "${file}")")
+  newFile=$(basename "${file}")
+  newFileExtn=$(echo "$newFile" | sed -re "s%.*\.%%")
+  newFileBase=$(basename "$newFile" ".$newFileExtn")
+
+  # find/replace
+  if [[ ! -z "$find" ]]
   then
-    new_file=`echo $new_file | sed -e "s%$find%$repl%g"`
+    if [[ "${regex}" == "true" ]]
+    then
+      newFileBase=$(echo ${newFileBase} | sed -re "s%$find%$replace%g")
+    else
+      newFileBase=$(echo ${newFileBase} | sed -e "s%$find%$replace%g")
+    fi
   fi
-  new_file=`echo $new_file | tr -d \'\"\, | sed "s% %_%g"` 
-  if [ ! -e $new_file ]
+
+  # Remove
+  for x in $(echo "${rm}")
+  do
+    newFileBase=$(echo "${newFileBase}" | sed "s%$x%%")
+  done
+
+  # format space and other
+  newFileBase=$(echo $newFileBase | tr -d \'\"\, | tr -s ". -" "_")
+  newFile="${newFileBase}.${newFileExtn}"
+
+  if [ ! -e "$newFile" ]
   then
-    echo "Rename '$file' as '$new_file'"
-    mv "$file" "$new_file"
+    echo "Rename '"$(basename "${file}")"' as '$newFile'"
+    mv "${file}" "${newFilePath}/${newFile}"
   fi
-done
+done < <(${cmd})
diff --git a/Ubuntu/bin/get b/Ubuntu/bin/get
--- a/Ubuntu/bin/get
+++ b/Ubuntu/bin/get
@@ -1,18 +1,63 @@
-#!/bin/bash
-if [[ $# -eq 0 ]]
+#!/bin/bash -e
+
+# -------------------------------------------------------------------------------------------------
+# Functions
+# -------------------------------------------------------------------------------------------------
+BASEDIR=$(dirname $(readlink -f ${0}))
+BASENAME=$(basename ${0})
+
+function usage {
+  echo "Usage: ${BASENAME} [<dir>] [<pattern to find>] [ -- <additional arguments to find>]"
+  echo "Default <dir>    : '.'"
+  echo "Default <pattern>: ''"
+  exit 0
+}
+
+function dieUsage {
+  echo "Error ${1}"
+  usage
+  exit 1
+}
+
+# -------------------------------------------------------------------------------------------------
+# Parse Arg
+# -------------------------------------------------------------------------------------------------
+if [[ ${#} -eq 1 && ("${1}" == "-h" || "${1}" == "--help") ]]
 then
-   echo "Usage: ${0} [ <dir> ] <pattern to find>"
-   exit 0
+  usage
 fi
 
-if [[ $# -eq 1 ]]
+# Declare an associative array
+# Add all arg before '--' in the array
+declare -a arg=()
+while [[ ! -z "$1" && "$1" != "--" ]]
+do
+  arg=("${arg[@]}" "$1")
+  shift
+done
+
+if [[ "$1" == "--" ]]
 then
-   dir="."
-   pattern=${1}
-elif [[ $# -eq 2 ]]
-then
-   dir=${1}
-   pattern=${2}
+  shift
 fi
 
-find $dir -name "$pattern" 
+# Now we have all the arguments before '--' in arg and the rest in $@  
+dir="."
+if [[ ${#arg[@]} -eq 1 ]]
+then
+  pattern=${arg[0]}
+elif [[ ${#arg[@]} -eq 2 ]]
+then
+  dir=${arg[0]}
+  pattern=${arg[1]}
+fi
+
+# -------------------------------------------------------------------------------------------------
+# Main
+# -------------------------------------------------------------------------------------------------
+if [[ ${#arg[@]} -eq 0 ]]
+then
+  find ${dir} "${@}"
+else
+  find ${dir} -name "$pattern" "${@}"
+fi
